// backend/tamiConfigurator.web.js
//
// Backend module called by the Tami_Configurator page when the user submits the
// configuration form embedded inside the iframe (configurator-wix.html).
//
// On a successful submission it:
//   1. Upserts the customer in the Wix CRM (so the team has a record).
//   2. Sends a confirmation email TO THE CUSTOMER (TEMPLATE_CUSTOMER).
//   3. Sends a notification email TO THE TEAM INBOX (TEMPLATE_DEV_TEAM),
//      using a dedicated CRM contact for info@lighthousetech.ch that is
//      resolved via queryContacts to avoid Wix merging it with the admin
//      profile (which would mis-deliver the mail to the admin's mailbox).
//
// Both triggered-email templates must be created in:
//   Wix Dashboard → Customer Management → Triggered Emails
// with matching variable names (see "variables" below).

import { Permissions, webMethod } from 'wix-web-module';
import { contacts, triggeredEmails } from 'wix-crm-backend';

// Internal contact for the Lighthouse Tech business mailbox that receives all
// new configuration notifications.
const TEAM_EMAIL = 'info@lighthousetech.ch';

// Triggered-email template IDs (auto-generated by Wix Dashboard → Triggered Emails)
const TEMPLATE_CUSTOMER = 'VJUfjJq'; // confirmation sent to the customer
const TEMPLATE_DEV_TEAM = 'VJUgQ97'; // notification sent to the dev team

export const submitConfiguration = webMethod(
  Permissions.Anyone,
  async (payload) => {
    if (!payload || typeof payload !== 'object') throw new Error('Invalid payload');
    const { size, colour, lens, name, email, country, address, notes, newsletter } = payload;

    if (!size || !colour || !lens)        throw new Error('Missing configuration selection');
    if (!name || !email)                  throw new Error('Missing customer details');
    if (!country || !address)             throw new Error('Missing shipping country or address');
    if (!/^\S+@\S+\.\S+$/.test(email))    throw new Error('Invalid email address');

    // ── 1) Upsert customer contact ──
    const [firstName, ...rest] = name.trim().split(/\s+/);
    const lastName = rest.join(' ') || ' ';

    let customerContactId;
    try {
      const result = await contacts.appendOrCreateContact({
        name:      { first: firstName, last: lastName },
        emails:    [{ email, primary: true, tag: 'MAIN' }],
        addresses: [{
          tag:     'SHIPPING',
          address: { addressLine: address, country }
        }],
        // Stored on the contact so the team can later filter/export newsletter
        // subscribers without leaving the Wix CRM.
        labelKeys: newsletter ? ['custom.newsletter-subscriber'] : []
      });
      customerContactId = result.contactId;
    } catch (e) {
      console.warn('Customer CRM upsert failed:', e);
    }

    // ── 2) Resolve the internal team contact for TEAM_EMAIL.
    //
    // We deliberately do NOT use appendOrCreateContact here: when the team
    // address belongs to the site owner (e.g. info@lighthousetech.ch), Wix's
    // contact merging logic conflates it with the admin's personal profile,
    // and the triggered email ends up being delivered to the admin's mailbox
    // instead of the team inbox. queryContacts + createContact gives us a
    // standalone "team notifications" contact that is guaranteed to deliver
    // to TEAM_EMAIL only.
    let teamContactId;
    try {
      const queryResult = await contacts
        .queryContacts()
        .eq('info.emails.email', TEAM_EMAIL)
        .find();

      const existing = queryResult.items.find(c =>
        (c.info?.emails?.items || []).some(e => e.email === TEAM_EMAIL)
      );

      if (existing) {
        teamContactId = existing._id;
      } else {
        const created = await contacts.createContact({
          name:   { first: 'Lighthouse', last: 'Tech Team' },
          emails: [{ email: TEAM_EMAIL, primary: true, tag: 'MAIN' }]
        });
        teamContactId = created._id;
      }
    } catch (e) {
      console.error('Team CRM lookup/create failed:', e);
    }

    // ── 3) Variables shared by both templates ──
    const variables = {
      size,
      colour,
      lens,
      customerName:    name,
      customerEmail:   email,
      customerCountry: country,
      customerAddress: address,
      notes:           notes && notes.length ? notes : '(none)',
      newsletter:      newsletter ? 'Yes' : 'No'
    };

    // ── 4) Fire both emails. We do NOT fail the whole submission if one fails;
    //       we log the error and still return ok so the user sees the success
    //       screen. The CRM record remains as a backup. ──
    const sendResults = await Promise.allSettled([
      customerContactId
        ? triggeredEmails.emailContact(TEMPLATE_CUSTOMER, customerContactId, { variables })
        : Promise.reject(new Error('No customer contact id')),
      teamContactId
        ? triggeredEmails.emailContact(TEMPLATE_DEV_TEAM, teamContactId, { variables })
        : Promise.reject(new Error('No team contact id'))
    ]);

    sendResults.forEach((r, i) => {
      if (r.status === 'rejected') {
        const target = i === 0 ? 'customer' : 'team';
        console.error(`Triggered email to ${target} failed:`, r.reason);
      }
    });

    console.log('[tamiConfigurator] customerContactId:', customerContactId);
    console.log('[tamiConfigurator] teamContactId    :', teamContactId);
    console.log('[tamiConfigurator] sendResults      :', sendResults.map(r => r.status));

    // If BOTH emails failed, surface a server error so the user retries.
    const allFailed = sendResults.every(r => r.status === 'rejected');
    if (allFailed) throw new Error('Email delivery failed. Please try again.');

    return {
      ok: true,
      customerContactId,
      teamContactId,
      customerEmailSent: sendResults[0].status === 'fulfilled',
      teamEmailSent:     sendResults[1].status === 'fulfilled'
    };
  }
);
